<a href="https://colab.research.google.com/github/Darkunquie/my-projects/blob/main/NUMPY_PRACTICe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import time

In [ ]:
time = time.time()
print(time)

1732339901.3958185


##1. Creating numpy arrays

list

In [ ]:
a=[1,2,3,4,5]
print(a)

[1, 2, 3, 4, 5]


In [ ]:
a.append(789)

In [ ]:
a

[1, 2, 3, 4, 5, 789]

In [ ]:
type(a)

list

In [ ]:
a2=np.array(a)
a2

array([  1,   2,   3,   4,   5, 789])

In [ ]:
#maths operation on numpy
import numpy as np
a2 = np.array([1, 2, 3])
b = a2 * 2  # Result: array([2, 4, 6])
b

array([2, 4, 6])

In [ ]:
a2=np.array(a)
a2*345

array([   345,    690,   1035,   1380,   1725, 272205])

In [ ]:
#mean

In [ ]:
mean=np.mean(a2)
mean

134.0

In [ ]:
#matrix multiplication
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[1,2],[3,4],[5,6]])
np.dot(c,d)

array([[22, 28],
       [49, 64]])

In [ ]:
np.shape(a2)


(6,)

In [ ]:
a2.reshape(2,3)

array([[  1,   2,   3],
       [  4,   5, 789]])

In [ ]:
a2.reshape(3,2)
a2[2:-2]

array([3, 4])

##Using arange

##arange is a function provided by the NumPy library that creates an array of evenly spaced values within a specified range

In [ ]:
a = np.arange(0, #starting number
              10) #Stop number - excluded
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Specifying a Step:
arr3 = np.arange(0, # start
                  20,#end
                  3)# differences
arr3

array([ 0,  3,  6,  9, 12, 15, 18])

In [ ]:
#create an array with non integer steps
np.arange(0, 20, 1.5)


array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5, 15. ,
       16.5, 18. , 19.5])

##Array using 0s and 1s

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

##Argument: (4, 6, 2)

This tuple specifies the shape of the array you want to create. In this case:

4 is the size of the first dimension (the number of depth layers).

6 is the size of the second dimension (the number of rows).

2 is the size of the third dimension (the number of columns).

In [ ]:
np.ones((4,6,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
#linspace
np.linspace(1, #start number
            10, #Last number - not excluded
            5)  #How many numbe

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
#eye matrix
# np.eye(N, M=None, k=0, dtype=float) syntax
#N: Number of rows in the output matrix.
#M: (optional) Number of columns in the output matrix. If not provided, it defaults to N, creating a square matrix.
#k: (optional) The index of the diagonal. The default is 0 (the main diagonal), k > 0 refers to an upper diagonal, and k < 0 refers to a lower diagonal.
#dtype: (optional) The desired data type for the output array. By default, it is float.



np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(4,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

In [4]:
#non identity matrix
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [5]:
#Creating an Identity Matrix with a Different Diagonal:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [6]:
np.eye(3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [7]:
np.eye(3, k=-2)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.]])

In [11]:
np.eye(3,k=-3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
#change datatype
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

##2. Array using random numbers

In [17]:
np.random.rand(3)
a=np.random.rand(3)
a

array([0.85279115, 0.76654797, 0.90380322])

In [18]:
#Creating a 2D array with standard normal random numbers
np.random.randn(3, 4)


array([[ 0.14333525, -1.07775029, -0.07732794,  1.20111562],
       [-0.02054268, -0.18762874, -1.03934595,  0.39483769],
       [-0.37414761,  0.01364448,  1.00756444,  0.71467143]])

In [19]:
x = 0.42014271
type(x)

float

In [20]:
np.random.randint(1,100)

40

In [22]:
np.random.randint(1,100,size=66)

array([66, 39, 52, 78, 90, 84, 97, 28, 13, 91, 43, 31, 44, 45, 25, 53, 40,
       49, 85, 41, 19, 93, 41, 35, 53, 64, 87, 63, 84, 80, 93, 92, 15, 45,
       23, 61, 34, 63, 34,  3, 73, 42, 63, 84, 82, 39,  2, 32, 39, 32,  8,
       84, 60, 14, 72, 81, 39, 51, 80, 42, 87, 84, 79, 83, 44,  9])

In [24]:
np.random.randint(1,100,size=(3,#rows
                              4))#col

array([[83,  7, 64, 86],
       [59, 11, 68, 32],
       [14, 91, 34, 66]])

In [25]:
np.random.randint(1,100,size=(3,#dimenisions
                              4,2))

array([[[77, 70],
        [20, 47],
        [76, 51],
        [91, 98]],

       [[ 4, 76],
        [73, 74],
        [ 2, 17],
        [26, 20]],

       [[56, 19],
        [22, 89],
        [ 9, 21],
        [17, 43]]])

In [26]:
np.random.random((3,4))#float values

array([[0.22190555, 0.02550879, 0.1871965 , 0.10665334],
       [0.04223266, 0.28369538, 0.86489005, 0.27343397],
       [0.03590286, 0.17089284, 0.2623333 , 0.35777231]])

randn - Using normal distribution

In [27]:
np.random.randn(3,4)

array([[ 0.85990136,  1.0185717 , -0.21923202, -0.44464373],
       [ 0.83641407, -0.42438054, -0.64731034,  0.26878508],
       [-0.80117635, -0.46772083,  0.6676383 ,  1.66157871]])

In [28]:
np.random.randint(5,#start
                  20,#end
                  6)# size

array([ 5, 11,  6, 11, 16, 15])

In [29]:
np.random.randint(5,20,(5,4))

array([[ 6, 19,  5,  7],
       [ 9, 10,  9,  6],
       [11, 16,  6, 16],
       [14, 17, 12, 17],
       [17,  6,  8, 14]])

Seed - Bringing sanity to randomness

A seed is an initial value used to initialize a pseudorandom number generator (PRNG). When you set the seed for a random number generator, you set its starting point, and this determines the sequence of random numbers that will be generated.

In [32]:
#to set seed value
np.random.seed(101)
np.random.rand(4)



array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [33]:
np.random.seed(101)
np.random.randint(1,100,size=(3,4))

array([[96, 12, 82, 71],
       [64, 88, 76, 10],
       [78, 41,  5, 64]])

In [34]:
np.random.randint(1,100,3)

array([41, 61, 93])

In [35]:
np.random.seed(1)
np.random.randint(1,100,3)

array([38, 13, 73])

##3. Array methods and attributes

In [37]:
#shape
a=np.arange(1,
            25)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [50]:
#ndarray.shape
arr=np.array([[1, 2, 3], [4, 5, 6]])
arr.shape

(2, 3)

np.random.randn: This function generates samples from the standard normal distribution (mean = 0, standard deviation = 1). The shape of the output array is specified by the arguments provided.

In [40]:
b = np.random.randn(4, 3)
b

array([[-0.52817175, -1.07296862,  0.86540763],
       [-2.3015387 ,  1.74481176, -0.7612069 ],
       [ 0.3190391 , -0.24937038,  1.46210794],
       [-2.06014071, -0.3224172 , -0.38405435]])

In [47]:
c = np.random.randint(1,3)
c

2

ndarray.ndim:

Returns the number of dimensions (axes) of the array.

In [51]:
np.ndim(arr)

2

In [52]:
arr.shape

(2, 3)

In [55]:
print(arr.size)

6


In [56]:
a.size

24

In [58]:
#dtype
a.dtype
arr.dtype

dtype('int64')

In [59]:
arr.dtype

dtype('int64')

In [60]:
#ndarray.itemsize Returns the size (in bytes) of each element in the array.
arr.itemsize

8

In [ ]:
#ndarray.nbytes:

#Returns the total number of bytes consumed by the elements of the array.

In [61]:
arr.nbytes

48

In [62]:
a.nbytes

192

In [64]:
arr.T  # transpose matrix

array([[1, 4],
       [2, 5],
       [3, 6]])

In [65]:
#max, min, argmax and argmin
arr.max()

6

In [67]:
a.max()

24

In [74]:
mat=np.random.randn(3,4)
mat

array([[-0.60998525,  0.30641238,  1.69182613, -0.74795374],
       [-0.58079722, -0.11075397,  2.04202875,  0.44752069],
       [ 0.68338423,  0.02288597,  0.85723427,  0.18393058]])

In [73]:
mat.T

array([[ 0.87341823, -1.05825656,  0.103163  ],
       [-0.11138337,  0.65628408, -0.62166685],
       [-1.03803876, -0.06249159,  0.27571804],
       [-1.00947983, -1.73865429, -1.09067489]])

In [75]:
a.argmax() #The method argmax() in NumPy is used to find the index of the maximum value in an array

23

In [ ]:
#Purpose:

#It returns the index of the first occurrence of the maximum value in the array.

In [76]:
np.argmax(mat)

6

In [81]:
d=np.random.randint(2,20,5)
d

array([13, 14, 13,  6,  9])

In [82]:
d.argmax()

1

In [83]:
d.min()

6

In [86]:
val=d.argmin()
val

3

In [87]:
d[val] #accessing the value

6

Array Methods

ndarray.reshape(new_shape):

Gives a new shape to the array without changing its data.

In [90]:
arr1=np.random.rand(4,3)
arr1

array([[0.62169572, 0.11474597, 0.94948926],
       [0.44991213, 0.57838961, 0.4081368 ],
       [0.23702698, 0.90337952, 0.57367949],
       [0.00287033, 0.61714491, 0.3266449 ]])

In [93]:
reshaped_arr = arr1.reshape(3,4)
print(reshaped_arr)

[[0.62169572 0.11474597 0.94948926 0.44991213]
 [0.57838961 0.4081368  0.23702698 0.90337952]
 [0.57367949 0.00287033 0.61714491 0.3266449 ]]


ndarray.flatten():

Returns a copy of the array collapsed into one dimension.

In [95]:
arr1.flatten()

array([0.62169572, 0.11474597, 0.94948926, 0.44991213, 0.57838961,
       0.4081368 , 0.23702698, 0.90337952, 0.57367949, 0.00287033,
       0.61714491, 0.3266449 ])

ndarray.sum(axis=None):

Returns the sum of array elements over a given axis.

In [96]:
arr1.sum(axis=0)

array([1.31150516, 2.21366002, 2.25795045])

In [98]:
arr1.sum(axis=1) #row wise sum

array([1.68593095, 1.43643855, 1.71408599, 0.94666014])

ndarray.mean(axis=None):

Returns the arithmetic mean of the array elements along a specified axis.

In [103]:
arr.mean(axis=0)

array([2.5, 3.5, 4.5])

In [105]:
arr.max()

6

In [110]:
arr.sort(axis=0)
arr

array([[1, 2, 3],
       [4, 5, 6]])

##4. Indexing and Slicing

In [111]:
a = np.arange(11,25)
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [112]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[1, 2])  # Output: 6 (element at second row, third column)


6


In [113]:
a[2:6]

array([13, 14, 15, 16])

In [114]:
#Specific elements
a[[0,3,6]]

array([11, 14, 17])

In [115]:
arr_2d[2]  #accessing whole row

array([7, 8, 9])

In [119]:
arr_2d[2] =arr_2d[2][::-1]
arr_2d #reverse row

array([[1, 2, 3],
       [4, 5, 6],
       [9, 8, 7]])

In [116]:
#Updating specific elements
a[3:5] = 100
a

array([ 11,  12,  13, 100, 100,  16,  17,  18,  19,  20,  21,  22,  23,
        24])

Two dimensional array indexing and slicing

In [120]:
b = np.array([[10,32,6,7,8], [90, 45, 32 , 89, 50],
              [33, 66, 99, 22, 55], [23, 56, 98, 45, 65]])
b

array([[10, 32,  6,  7,  8],
       [90, 45, 32, 89, 50],
       [33, 66, 99, 22, 55],
       [23, 56, 98, 45, 65]])

In [121]:
#indexing row
b[1]

array([90, 45, 32, 89, 50])

In [122]:
#Same as above
b[2,3]

22

In [130]:
b[1][::-1]

array([50, 89, 32, 45, 90])

In [132]:
#Specific rows and columns
b
b[:2,2:-1]

array([[ 6,  7],
       [32, 89]])

Basic Slicing

In [136]:
import numpy as np

arr_1d = np.array([10, 20, 30, 40, 50])
print(arr_1d[0])  # Output: 10 (first element)
print(arr_1d[3])  # Output: 40 (fourth element)


10
40


In [137]:
print(arr_1d[1:4])  # Output: [20 30 40] (elements from index 1 to 3)


[20 30 40]


In [138]:
b[0:2,1:3]  #matrix slicing
# (elements from row 0 to 1 and column 1 to 2)

array([[32,  6],
       [45, 32]])

Custom indexing

In [139]:
b = np.array([[10,32,6,7,8], [90, 45, 32 , 89, 50],
              [33, 66, 99, 22, 55], [23, 56, 98, 45, 65]])
b

array([[10, 32,  6,  7,  8],
       [90, 45, 32, 89, 50],
       [33, 66, 99, 22, 55],
       [23, 56, 98, 45, 65]])

In [141]:
b[:,(1,3)] #All Rows, (1 Coloumn, 3 Coloumn)

array([[32,  7],
       [45, 89],
       [66, 22],
       [56, 45]])

In [143]:
b[:3,(1,3)] #only 3  Rows, (1 Coloumn, 3 Coloumn)

array([[32,  7],
       [45, 89],
       [66, 22]])

subset

In [144]:
b

array([[10, 32,  6,  7,  8],
       [90, 45, 32, 89, 50],
       [33, 66, 99, 22, 55],
       [23, 56, 98, 45, 65]])

In [153]:
c = b[1:3,2:-1]#b[1:3, ...]: This part indicates that you want to select rows from index 1 to index 2.


c

array([[32, 89],
       [99, 22]])

In [154]:
#copy
d = b[:2,1:].copy()
d

array([[32,  6,  7,  8],
       [45, 32, 89, 50]])

In [155]:
d

array([[32,  6,  7,  8],
       [45, 32, 89, 50]])

selection

In [156]:
a = np.arange(30, 45)
a

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [157]:
b = a < 40
b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False])

In [160]:
a[b]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [161]:
c = a[a < 35]
c

array([30, 31, 32, 33, 34])

##5. NumPy Operations

In [162]:
a = np.arange(10, 25)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [163]:
a+a

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [164]:
a**a

array([         10000000000,         285311670611,        8916100448256,
            302875106592253,    11112006825558016,   437893890380859375,
                          0, -2863221430593058543,  -497033925936021504,
        6353754964178307979, -2101438300051996672, -1595931050845505211,
        4981753131911086080,  8450172506621111015,                    0])

In [166]:
np.exp(a) #Exponent of each element

array([2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
       1.20260428e+06, 3.26901737e+06, 8.88611052e+06, 2.41549528e+07,
       6.56599691e+07, 1.78482301e+08, 4.85165195e+08, 1.31881573e+09,
       3.58491285e+09, 9.74480345e+09, 2.64891221e+10])

In [167]:
np.sqrt(a)  #Square root of each element

array([3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949])

In [168]:
np.square(a) #Square of each element

array([100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484,
       529, 576])

In [169]:
np.sin(a)  #Trignometric sine

array([-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721,
        0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836])

In [170]:
np.log(a)  #log

array([2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383])

In [171]:
np.mean(a)

17.0

python

data = np.array([1, 2, 3, 4, 5])

sum_data = np.sum(data)           # Output: 15
mean_data = np.mean(data)         # Output: 3.0
median_data = np.median(data)     # Output: 3.0
std_dev_data = np.std(data)       # Output: 1.41421356
variance_data = np.var(data)  

In [172]:
a = np.random.rand(4,5)
a

array([[0.5270581 , 0.8859421 , 0.35726976, 0.90853515, 0.62336012],
       [0.01582124, 0.92943723, 0.69089692, 0.99732285, 0.17234051],
       [0.13713575, 0.93259546, 0.69681816, 0.06600017, 0.75546305],
       [0.75387619, 0.92302454, 0.71152476, 0.12427096, 0.01988013]])

In [173]:
np.round(a,2)  #rounding to 2 decimal places

array([[0.53, 0.89, 0.36, 0.91, 0.62],
       [0.02, 0.93, 0.69, 1.  , 0.17],
       [0.14, 0.93, 0.7 , 0.07, 0.76],
       [0.75, 0.92, 0.71, 0.12, 0.02]])

In [174]:
np.round(a)  #rounding to 0 decimal places

array([[1., 1., 0., 1., 1.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 0., 1.],
       [1., 1., 1., 0., 0.]])

In [175]:
np.std(a)  #Calculate standard variance

0.3433423334260191

In [176]:
np.var(a) #Calculate variance

0.11788395792242368

In [177]:
np.mean(a) #Mean / average

0.5614286579557584

In [178]:
np.unique(a)

array([0.01582124, 0.01988013, 0.06600017, 0.12427096, 0.13713575,
       0.17234051, 0.35726976, 0.5270581 , 0.62336012, 0.69089692,
       0.69681816, 0.71152476, 0.75387619, 0.75546305, 0.8859421 ,
       0.90853515, 0.92302454, 0.92943723, 0.93259546, 0.99732285])

In [180]:
# Create a 2D array and a 1D array
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([1, 2, 3])

# Broadcasting the 1D array B to the shape of A
C = A + B  # Output: array([[2, 4, 6], [5, 7, 9]])
C

array([[2, 4, 6],
       [5, 7, 9]])

##6. Storing and reading NumPy

Saving and Restoring

In [181]:
array_1 = np.arange(10, 20)
array_2 = np.arange(30,50, 3)

In [184]:
np.save('ar1file',  #File name , will be saved with .npy extension
        array_1 ) #Array to be saved

In [185]:
import numpy as np

# Create a NumPy array
array_1 = np.array([1, 2, 3, 4, 5])

# Save the array to a file
np.save('ar1file', array_1)

# The array is now saved to 'ar1file.npy'


In [186]:
loaded_array = np.load('ar1file.npy')
print(loaded_array)  # Output: [1 2 3 4 5]


[1 2 3 4 5]


In [183]:
!ls -l

total 8
-rw-r--r-- 1 root root  208 Nov 24 07:46 ar1file.npy
drwxr-xr-x 1 root root 4096 Nov 21 14:25 sample_data


In [187]:
np.load('ar1file.npy')

array([1, 2, 3, 4, 5])